server:
  port: 8182
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/sapientdb
    username: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
debug: true