server:
  port: 8090

spring:
  application: 
    name: hr-service
    
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${UREKA_SERVER_URL:http://localhost:8761/eureka/}
      
resilience4j.circuitbreaker:
    instances:
        config-hr:
            registerHealthIndicator: true
            slidingWindowSize: 4
            permittedNumberOfCallsInHalfOpenState: 2
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 100s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
            
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'