server:
  port: 8181
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/empdb
    username: root
  application:
    name: emp-service
    
  jpa:
    show-sql: true
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${UREKA_SERVER_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - prometheus